sensor.thermostat_temperature:
    friendly_name: Temperature
climate.thermostat_heating:
    friendly_name: Heat
climate.thermostat_cooling:
    friendly_name: AC
    
light.level:
    friendly_name: Hallway
    state_card_mode: break-slider-toggle
    stretch_slider: true
    
light.main:
    friendly_name: Main
    state_card_mode: break-slider-toggle
    stretch_slider: true
    
light.desk:
    friendly_name: Desk
    state_card_mode: break-slider-toggle
    stretch_slider: true
    
light.sengled_e11g13_031e1173_1:
    friendly_name: Sengled
    state_card_mode: break-slider-toggle
    stretch_slider: true

light.dc4f22e35c77_10009:
    friendly_name: Kitchen Left
    state_card_mode: break-slider-toggle
    stretch_slider: true

light.dc4f22e3e07c_10008:
    friendly_name: Kitchen Right
    state_card_mode: break-slider-toggle
    stretch_slider: true

light.dc4f22d3dbf9_100013:
    friendly_name: TV Light
    state_card_mode: break-slider-toggle
    stretch_slider: true

switch.zwaveswitch_1:
    friendly_name: ZWave Switch
    
lock.august:
    friendly_name: Front Door Lock
   
cover.garage_door_opener: 
    icon: mdi:car

light.sengled_e11n1ea_00031820_1:
  friendly_name: 1
light.sengled_e11n1ea_000359a2_1:
  friendly_name: 2
light.sengled_e11n1ea_00037429_1:
  friendly_name: 3
light.sengled_e11n1ea_0003b488_1:
  friendly_name: 4
light.sengled_e11n1ea_0003bff9_1:
  friendly_name: 5
light.sengled_e11n1ea_0004dd70_1:
  friendly_name: 6
light.sengled_e11n1ea_0004e0e5_1:
  friendly_name: 7
light.sengled_e11n1ea_0004e66d_1:
  friendly_name: 8

# group.bathroom:
#     hidden: true

group.hallLight1:
    hidden: true

group.hallLight2:
    hidden: true

group.hallLight3:
    hidden: true

group.bathroomHallwayLights:
    hidden: false

group.all_lights:
    hidden: false
    friendly_name: 'All Lights'

group.all_automations:
    hidden: false
    friendly_name: 'Automations'

group.all_scripts:
    hidden: false
    friendly_name: 'Scripts'