sensor.thermostat_temperature:
    friendly_name: Temperature
climate.thermostat_heating:
    friendly_name: Heat
climate.thermostat_cooling:
    friendly_name: AC
    
light.main:
    friendly_name: Main
    state_card_mode: break-slider-toggle
    stretch_slider: true
    
light.desk:
    friendly_name: Desk
    state_card_mode: break-slider-toggle
    stretch_slider: true
    
light.sengled_1:
    friendly_name: BathRoom
    state_card_mode: break-slider-toggle
    stretch_slider: true

light.dc4f22e35c77_100024:
    friendly_name: Kitchen Left
    state_card_mode: break-slider-toggle
    stretch_slider: true

light.dc4f22e3e07c_100017:
    friendly_name: Kitchen Right
    state_card_mode: break-slider-toggle
    stretch_slider: true

light.dc4f22d3dbf9_100021:
    friendly_name: TV Light
    state_card_mode: break-slider-toggle
    stretch_slider: true

switch.zwaveswitch_1:
    friendly_name: ZWave Switch
    
lock.august:
    friendly_name: Front Door Lock
   
cover.garage_door_opener: 
    icon: mdi:car

sensor.aeotec_temperature:
    friendly_name: Temperature
sensor.aeotec_luminance:
    friendly_name: Lux
sensor.aeotec_humidity:
    friendly_name: Humidity
sensor.aeotec_burglar:
    friendly_name: Vibration
binary_sensor.aeotec_motion:
    friendly_name: Motion

group.all_automations:
    hidden: false
    friendly_name: 'Automations'

group.all_scripts:
    hidden: false
    friendly_name: 'Scripts'