switch.c:
  name:
  platform: vesync
  unique_id: 0140be3d-316f-445b-82ca-c9faf1bde726
switch.d:
  name:
  platform: vesync
  unique_id: be81a5e9-fc2f-4af7-a317-bc77af732adb
switch.a:
  name:
  platform: vesync
  unique_id: 2d959259-6d71-4d3a-858b-31fa84f4bb10
switch.b:
  name:
  platform: vesync
  unique_id: f71b92b0-be5f-4533-9796-d3377fcbe810
binary_sensor.hank_hkzwdws01_doorwindow_sensor_sensor:
  name:
  platform: zwave
  unique_id: 22-72057594412007424
sensor.hank_hkzwdws01_doorwindow_sensor_alarm_type:
  name:
  platform: zwave
  unique_id: 22-72057594413072385
sensor.hank_hkzwdws01_doorwindow_sensor_alarm_level:
  name:
  platform: zwave
  unique_id: 22-72057594413072401
sensor.hank_hkzwdws01_doorwindow_sensor_sourcenodeid:
  name:
  platform: zwave
  unique_id: 22-72057594413072417
sensor.hank_hkzwdws01_doorwindow_sensor_access_control:
  name:
  platform: zwave
  unique_id: 22-72057594413072529
sensor.hank_hkzwdws01_doorwindow_sensor_burglar:
  name:
  platform: zwave
  unique_id: 22-72057594413072545
media_player.bedroom_speaker:
  name:
  platform: cast
  unique_id: 9572e617-cb0b-5aea-800c-72165335d9fa
sensor.alarm_type:
  name:
  platform: zwave
  unique_id: 23-72057594429849601
sensor.alarm_level:
  name:
  platform: zwave
  unique_id: 23-72057594429849617
binary_sensor.hank_hkzwdws01_doorwindow_sensor_sensor_2:
  name:
  platform: zwave
  unique_id: 23-72057594428784640
sensor.hank_hkzwdws01_doorwindow_sensor_sourcenodeid_2:
  name:
  platform: zwave
  unique_id: 23-72057594429849633
sensor.hank_hkzwdws01_doorwindow_sensor_access_control_2:
  name:
  platform: zwave
  unique_id: 23-72057594429849745
sensor.hank_hkzwdws01_doorwindow_sensor_burglar_2:
  name:
  platform: zwave
  unique_id: 23-72057594429849761
sensor.alarm_type_2:
  name:
  platform: zwave
  unique_id: 24-72057594446626817
sensor.alarm_level_2:
  name:
  platform: zwave
  unique_id: 24-72057594446626833
binary_sensor.hank_hkzwdws01_doorwindow_sensor_sensor_3:
  name:
  platform: zwave
  unique_id: 24-72057594445561856
sensor.hank_hkzwdws01_doorwindow_sensor_sourcenodeid_3:
  name:
  platform: zwave
  unique_id: 24-72057594446626849
sensor.hank_hkzwdws01_doorwindow_sensor_access_control_3:
  name:
  platform: zwave
  unique_id: 24-72057594446626961
sensor.hank_hkzwdws01_doorwindow_sensor_burglar_3:
  name:
  platform: zwave
  unique_id: 24-72057594446626977
sensor.alarm_type_3:
  name:
  platform: zwave
  unique_id: 25-72057594463404033
sensor.alarm_level_3:
  name:
  platform: zwave
  unique_id: 25-72057594463404049
binary_sensor.aeotec_motion_1:
  name: Motion
  platform: zwave
  unique_id: 25-72057594462339072
sensor.aeotec_temperature_1:
  name: Temperature
  platform: zwave
  unique_id: 25-72057594462355474
sensor.aeotec_luminance_1:
  name: Lux
  platform: zwave
  unique_id: 25-72057594462355506
sensor.aeotec_humidity_1:
  name: Humidity
  platform: zwave
  unique_id: 25-72057594462355538
sensor.aeotec_zw100_multisensor_6_ultraviolet:
  name:
  platform: zwave
  unique_id: 25-72057594462355890
sensor.aeotec_zw100_multisensor_6_sourcenodeid:
  name:
  platform: zwave
  unique_id: 25-72057594463404065
sensor.aeotec_zw100_multisensor_6_burglar:
  name:
  platform: zwave
  unique_id: 25-72057594463404193
climate.linear_gctbz48_battery_powered_zwave_thermostat_heating_1:
  name:
  platform: zwave
  unique_id: 26-72057594479427602
climate.linear_gctbz48_battery_powered_zwave_thermostat_cooling_1:
  name:
  platform: zwave
  unique_id: 26-72057594479427618
sensor.linear_gctbz48_battery_powered_zwave_thermostat_temperature:
  name:
  platform: zwave
  unique_id: 26-72057594479132690
light.level:
  name:
  platform: zwave
  unique_id: 27-72057594495729665
sensor.alarm_type_4:
  name:
  platform: zwave
  unique_id: 28-72057594513735681
sensor.alarm_level_4:
  name:
  platform: zwave
  unique_id: 28-72057594513735697
binary_sensor.hank_hkzwdws01_doorwindow_sensor_sensor_4:
  name:
  platform: zwave
  unique_id: 28-72057594512670720
switch.switch:
  name:
  platform: zwave
  unique_id: 29-72057594529267712
sensor.unknown:
  name:
  platform: zwave
  unique_id: 29-72057594529480706
sensor.zooz_zen15_power_switch_power:
  name:
  platform: zwave
  unique_id: 29-72057594529480834
sensor.zooz_zen15_power_switch_voltage:
  name:
  platform: zwave
  unique_id: 29-72057594529480962
sensor.zooz_zen15_power_switch_current:
  name:
  platform: zwave
  unique_id: 29-72057594529481026
sensor.zooz_zen15_power_switch_previous_reading:
  name:
  platform: zwave
  unique_id: 29-72057594529480722
light.level_2:
  name:
  platform: zwave
  unique_id: 30-72057594546061313
sensor.unknown_2:
  name:
  platform: zwave
  unique_id: 30-72057594546257922
light.fibaro_system_fgrgbwm441_rgbw_controller_level:
  name:
  platform: zwave
  unique_id: 30-144115188583989249
light.fibaro_system_fgrgbwm441_rgbw_controller_level_2:
  name:
  platform: zwave
  unique_id: 30-216172782621917185
light.fibaro_system_fgrgbwm441_rgbw_controller_level_3:
  name:
  platform: zwave
  unique_id: 30-288230376659845121
light.fibaro_system_fgrgbwm441_rgbw_controller_level_4:
  name:
  platform: zwave
  unique_id: 30-360287970697773057
light.fibaro_system_fgrgbwm441_rgbw_controller_level_5:
  name:
  platform: zwave
  unique_id: 30-432345564735700993
sensor.fibaro_system_fgrgbwm441_rgbw_controller_power:
  name:
  platform: zwave
  unique_id: 30-72057594546258050
sensor.fibaro_system_fgrgbwm441_rgbw_controller_exporting:
  name:
  platform: zwave
  unique_id: 30-72057594546258432
sensor.fibaro_system_fgrgbwm441_rgbw_controller_power_2:
  name:
  platform: zwave
  unique_id: 30-72057594546241602
sensor.hank_hkzwdws01_doorwindow_sensor_sourcenodeid_4:
  name:
  platform: zwave
  unique_id: 28-72057594513735713
sensor.hank_hkzwdws01_doorwindow_sensor_access_control_4:
  name:
  platform: zwave
  unique_id: 28-72057594513735825
sensor.hank_hkzwdws01_doorwindow_sensor_burglar_4:
  name:
  platform: zwave
  unique_id: 28-72057594513735841
light.level_3:
  name:
  platform: zwave
  unique_id: 31-72057594562838529
sensor.unknown_3:
  name:
  platform: zwave
  unique_id: 31-72057594563035138
light.fibaro_system_fgrgbwm441_rgbw_controller_level_6:
  name:
  platform: zwave
  unique_id: 31-144115188600766465
light.fibaro_system_fgrgbwm441_rgbw_controller_level_7:
  name:
  platform: zwave
  unique_id: 31-216172782638694401
light.fibaro_system_fgrgbwm441_rgbw_controller_level_8:
  name:
  platform: zwave
  unique_id: 31-288230376676622337
light.fibaro_system_fgrgbwm441_rgbw_controller_level_9:
  name:
  platform: zwave
  unique_id: 31-360287970714550273
light.fibaro_system_fgrgbwm441_rgbw_controller_level_10:
  name:
  platform: zwave
  unique_id: 31-432345564752478209
sensor.fibaro_system_fgrgbwm441_rgbw_controller_power_3:
  name:
  platform: zwave
  unique_id: 31-72057594563035266
sensor.fibaro_system_fgrgbwm441_rgbw_controller_exporting_2:
  name:
  platform: zwave
  unique_id: 31-72057594563035648
sensor.fibaro_system_fgrgbwm441_rgbw_controller_power_4:
  name:
  platform: zwave
  unique_id: 31-72057594563018818
media_player.chromecast:
  name:
  platform: cast
  unique_id: 669683b8-4a0a-486a-9746-733596514c6a
media_player.plex_web_chrome:
  name:
  platform: plex
  unique_id: t2xptmksnuj
media_player.bedroom:
  name:
  platform: plex
  unique_id: 4d3aff45ab78c6028ce4d8ae75213082
lock.locked:
  name:
  platform: zwave
  unique_id: 32-72057594580598784
lock.locked_2:
  name:
  platform: zwave
  unique_id: 33-72057594597376000
sensor.alarm_type_5:
  name:
  platform: zwave
  unique_id: 33-72057594597621761
sensor.alarm_level_5:
  name:
  platform: zwave
  unique_id: 33-72057594597621777
lock.august:
  name:
  platform: zwave
  unique_id: 34-72057594614153216
sensor.alarm_type_6:
  name:
  platform: zwave
  unique_id: 34-72057594614398977
sensor.alarm_level_6:
  name:
  platform: zwave
  unique_id: 34-72057594614398993
sensor.lock_sourcenodeid:
  name:
  platform: zwave
  unique_id: 34-72057594614399009
sensor.lock_access_control:
  name:
  platform: zwave
  unique_id: 34-72057594614399121
light.sengled_e11g13_031e1173_1:
  name:
  platform: zha
  unique_id: b0:ce:18:14:03:1e:11:73-1
