default_view:
    view: yes
    name: Control
    entities: 
        - weather.dark_sky
        - group.users
        - group.aeotecSensor
        - group.doors
        - group.thermostat
        - group.switches
        - group.kitchenLights
        - group.all_automations
        - group.all_scripts
users:
    name: Users
    entities:
        - device_tracker.admin_pixel
        - device_tracker.admin_blackberry
        
aeotecSensor:
    name: Sensors
    entities:
        - sensor.aeotec_temperature
        - sensor.aeotec_luminance
        - sensor.aeotec_humidity
        - sensor.aeotec_vibration
        - binary_sensor.aeotec_motion
        
doors:
    name: Doors
    entities:
        - sensor.front_door_status
        - lock.august
        - sensor.basementdoor
 #       - cover.garage_door_opener

thermostat:
    name: Thermostat
    entities:
        - sensor.thermostat_temperature
        - climate.thermostat_cooling
        - climate.thermostat_heating
    
kitchenLights:
    name: Kitchen Lights
    entities:
        - light.dc4f22e35c77_10009
        - light.dc4f22e3e07c_10008

switches:
    name: Switches
    entities:
        - switch.d
        - light.desk
        - light.main
        - switch.zwaveswitch_1
        - light.dc4f22e35c77_10009
        - light.dc4f22e3e07c_10008
        - light.dc4f22d3dbf9_100013
        - light.sengled_1

# harmony:
#     name: Harmony
#     entities:
#         - sensor.harmony_status
#         - remote.harmony_hub

################## Tabs ##################
#firstFloor:
#    view: yes
#    name: First Floor
#    entities:
#        - group.users
#        - group.weatherSensor
#        - group.doors
#        - group.lights
#        - group.thermostat

#control:
#    view: yes
#    name: Control
#    entities:
#        - group.users
#        - group.owntrack
#        - group.weatherSensor
#        - group.aeotecSensor
#        - group.doors
#        - group.thermostat
#        - group.lights
#        - group.bedroomSwitches
#        - group.harmony
#        - group.systemMonitor
#        - group.all_automations
#        - group.all_scripts