

pr_bt_2ee3:
  hide_if_away: false
  icon:
  mac: BT_00:1F:FF:6F:73:18
  name: PR BT 2EE3
  picture:
  track: true

tv_bed_uhd:
  hide_if_away: false
  icon:
  mac: BT_F8:04:2E:94:B1:53
  name: '[TV] Bed UHD'
  picture:
  track: true

lge_dtv_bcm20702a1:
  hide_if_away: false
  icon:
  mac: BT_C8:29:2A:FF:D4:E9
  name: LGE DTV BCM20702A1
  picture:
  track: true

tv_samsung_6_series_43:
  hide_if_away: false
  icon:
  mac: BT_C0:97:27:0D:2E:F9
  name: '[TV] Samsung 6 Series (43)'
  picture:
  track: true

dtvbluetooth:
  hide_if_away: false
  icon:
  mac: BT_48:44:F7:2F:1E:75
  name: DTVBluetooth
  picture:
  track: true

pixel_3:
  hide_if_away: false
  icon:
  mac: BT_3C:28:6D:29:3A:2A
  name: Pixel 3
  picture:
  track: true

admin_pixel:
  hide_if_away: false
  icon:
  mac: 3C:28:6D:29:3A:2B
  name: Pixel 3
  picture:
  track: true

admin_blackberry:
  hide_if_away: false
  icon:
  mac:
  name: BlackBerry
  picture:
  track: true

pixel:
  hide_if_away: false
  icon:
  mac: BT_40:4E:36:53:87:B2
  name: Pixel
  picture:
  track: true

z557bl:
  hide_if_away: false
  icon:
  mac: BT_F8:A3:4F:9C:31:46
  name: Z557BL
  picture:
  track: true
