
pixel:
  hide_if_away: false
  icon:
  mac: AC:37:43:DE:F9:10
  name: Pixel
  picture:
  track: true

pixel_bt:
  hide_if_away: false
  icon:
  mac: BT_40:4E:36:53:87:B2
  name: Pixel 603-770-6823 (Bluetooth)
  picture:
  track: true

iphone:
  hide_if_away: false
  icon:
  mac: 6C:96:CF:D0:10:65
  name: IPhone
  picture:
  track: true

iphone_bt:
  hide_if_away: false
  icon:
  mac: BT_6C:96:CF:D0:10:66
  name: IPhone 603-867-2001
  picture:
  track: true
  
blackberry:
  hide_if_away: false
  icon:
  mac: CC:FD:17:F0:83:8C
  name: BlackBerry
  picture:
  track: true

blackberry_bt:
  hide_if_away: false
  icon:
  mac: BT_CC:FD:17:F0:83:8A
  name: BlackBerry 603-770-9757 (Bluetooth)
  picture:
  track: true
  
nancys_iphone:
  hide_if_away: false
  icon:
  mac: BT_CC:44:63:38:26:E2
  name: Nancy's iPhone
  picture:
  track: true

plt_bbtpro:
  hide_if_away: false
  icon:
  mac: BT_E4:22:A5:18:25:1E
  name: PLT BBTPRO
  picture:
  track: true

us8yqt2h2:
  hide_if_away: false
  icon:
  mac: BT_14:AB:C5:C3:6E:59
  name: US-8YQT2H2
  picture:
  track: true

iphone_2:
  hide_if_away: false
  icon:
  mac: BT_88:66:A5:EF:0D:70
  name: iPhone
  picture:
  track: true

admin_pixel:
  hide_if_away: false
  icon:
  mac: AC:37:43:DE:F9:10
  name: Pixel
  picture:
  track: true

admin_blackberry:
  hide_if_away: false
  icon:
  mac: CC:FD:17:F0:83:8C
  name: Backberry
  picture:
  track: true
