evening_mode:
  sequence:
    - service: switch.turn_on
      entity_id: 
        - switch.d
    - service: light.turn_on
      entity_id: 
        - light.desk
        - light.main
    # - service: light.turn_on
    #   entity_id:
    #     - light.sengled_7
    #     - light.sengled_8
    #   data:
    #       brightness: 40

night_mode:
  sequence:
    - service: switch.turn_off
      entity_id: 
        - switch.d
    - service: light.turn_off
      entity_id: 
        - light.dc4f22e35c77_10009
        - light.dc4f22e3e07c_10008
        - light.desk
        - light.main

day_mode:
  sequence:
    - service: light.turn_on
      entity_id: 
        - light.dc4f22e35c77_10009
        - light.dc4f22e3e07c_10008
      
leave:
  sequence:
    - service: switch.turn_off
      entity_id: 
        - switch.zwaveswitch_1
        - switch.a
        - switch.d

return:
  sequence:
    - service: switch.turn_on
      entity_id: 
        - switch.zwaveswitch_1
        - switch.a

# green_purple:
#   sequence:
#     - service: light.turn_on
#       entity_id: group.group1Lights
#       data:
#           color_name: purple
#     - service: light.turn_on
#       entity_id: group.group2Lights
#       data:
#           color_name: green

# thermostat_mode_setter:
#   sequence:
#     - service: input_boolean.turn_off
#       data_template:
#         entity_id: 
#           - '{{ off_one }}'
#           - '{{ off_two }}'
#     - service: input_boolean.turn_on
#       data_template:
#         entity_id: '{{ on_one }}'