- platform: vesync
  username: christian.everett1@gmail.com
  password: 6037706823
- platform: mqtt
  name: "TestSwitch"
  command_topic: "cmnd/sonoff/power"
  state_topic: "stat/sonoff/POWER"
  payload_on: "ON"
  payload_off: "OFF"